(function(){
 'use strict';
 const $=id=>document.getElementById(id), ids={trabzonspor:'f9ccbebd-8724-4bb5-ab17-9b4e4cea49f7',sebat:'04bfa175-c483-4b3c-8f79-6a59e2af1392'};
 const state={team:'trabzonspor',view:'overview',feeds:[],manual:[],manualStandings:[],loading:false,lastFetchFailed:false};
 let client=null,channel=null,poll=null,dialogMatch=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeUrl=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:'';}catch{return '';}};
 const stamp=s=>s?new Date(s).getTime():NaN;
 const date=s=>Number.isFinite(stamp(s))?new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Istanbul'}).format(new Date(s)):'Tarih açıklanmadı';
 const time=s=>Number.isFinite(stamp(s))?new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(s)):'';
 const own=(name,team=state.team)=>team==='trabzonspor'?/trabzonspor/i.test(name):/sebat/i.test(name);
 const teamName=()=>state.team==='trabzonspor'?'Trabzonspor':'Sebatspor';
 const name=s=>/^sebat spor k[üu]l[üu]b[üu]$/i.test(String(s||'').trim())?'Sebatspor':s;
 const currentFeed=()=>state.feeds.find(f=>f.team_id===ids[state.team]);
 function image(src,alt,cls=''){const u=safeUrl(src);return u?`<img src="${esc(u)}" alt="${esc(alt)}" class="${cls}" loading="lazy" onerror="this.hidden=true">`:'';}
 function club(m,side){const n=name(m[side]);return `<div class="mc-club">${image(m[side+'_logo'],'')||'<span class="mc-crest-fallback" aria-hidden="true">'+esc(n.split(' ').map(s=>s[0]).slice(0,2).join(''))+'</span>'}<strong>${esc(n)}</strong></div>`;}
 function status(m){if(m.status==='finished')return 'Maç sonu';if(m.status==='postponed')return 'Ertelendi';if(m.status==='cancelled')return 'İptal';if(m.status==='live'){return Date.now()-stamp(currentFeed()?.last_success_at)<180000?'Canlı':'Güncelleniyor';}if(stamp(m.date)<Date.now())return 'Sonuç bekleniyor';return 'Planlandı';}
 function score(m){return m.home_score!==null&&m.home_score!==undefined&&m.away_score!==null&&m.away_score!==undefined?`${esc(m.home_score)} – ${esc(m.away_score)}`:time(m.date)||'–';}
 function matches(){const feed=currentFeed()?.data||{};const all=(feed.matches||[]).map(m=>({...m}));for(const m of state.manual.filter(m=>m.team_id===ids[state.team])){const home=m.home_away!=='away';const n=teamName();const id=m.external_match_id||m.id;const index=all.findIndex(x=>x.id===id);const original=index>=0?all[index]:{};const manual={...original,id,home:home?n:m.opponent_name,away:home?m.opponent_name:n,home_logo:home?feed.team_logo:m.opponent_logo_url||original.home_logo,away_logo:home?m.opponent_logo_url||original.away_logo:feed.team_logo,home_score:home?m.home_score:m.away_score,away_score:home?m.away_score:m.home_score,date:m.match_date,status:m.status,venue:m.venue||original.venue,url:m.match_url||original.url,details:original.details||{},manual:true};if(index>=0)all[index]=manual;else all.push(manual);}return all.sort((a,b)=>(a.round||999)-(b.round||999)||(stamp(a.date)||Infinity)-(stamp(b.date)||Infinity));}
 function matchCard(m,label){if(!m)return `<article class="mc-match"><div class="mc-match-top"><strong>${esc(label)}</strong></div><div class="mc-empty">Bu bölüm için yayımlanmış maç bulunmuyor.</div></article>`;return `<article class="mc-match"><div class="mc-match-top"><strong>${esc(label)}</strong><span>${m.round?m.round+'. hafta':''}</span></div><div class="mc-match-body"><div class="mc-scoreboard">${club(m,'home')}<div class="mc-score">${score(m)}<small>${m.home_score!=null?'SKOR':'BAŞLAMA'}</small></div>${club(m,'away')}</div><p class="mc-match-date">${esc(m.date?date(m.date):m.date_label||'Tarih açıklanmadı')}${m.home_score!=null&&m.date?' · '+time(m.date):''}</p><div class="mc-match-actions"><span class="mc-pill ${esc(m.status)}">${esc(status(m))}</span><button class="mc-detail-btn" type="button" data-match="${esc(m.id)}">Maç detayları ↗</button></div></div></article>`;}
 function row(m){return `<button class="mc-match-row" type="button" data-match="${esc(m.id)}" aria-label="${esc(name(m.home)+' – '+name(m.away)+', '+status(m)+', maç detayları')}"><time>${esc(m.date?date(m.date):m.date_label||'Tarih bekleniyor')}<span> ${m.date?time(m.date):''}</span></time><span class="mc-row-team">${image(m.home_logo,'')}${esc(name(m.home))}</span><span class="mc-row-score">${score(m)}</span><span class="mc-row-team away">${esc(name(m.away))}${image(m.away_logo,'')}</span><span class="mc-pill ${esc(m.status)}">${esc(status(m))}</span></button>`;}
 function formHTML(list){return '<span class="mc-form" aria-label="Son maç sonuçları">'+list.slice(-5).map(m=>{const a=own(m.home)?m.home_score:m.away_score,b=own(m.home)?m.away_score:m.home_score;if(a==null||b==null)return '';const s=a>b?'w':a<b?'l':'d';return `<i class="${s}" title="${s==='w'?'Galibiyet':s==='l'?'Mağlubiyet':'Beraberlik'}">${s==='w'?'G':s==='l'?'M':'B'}</i>`;}).join('')+'</span>';}
 function renderOverview(list,table){const finished=list.filter(m=>m.status==='finished'),live=list.find(m=>m.status==='live'),next=list.find(m=>m.status==='scheduled'&&(!m.date||stamp(m.date)>Date.now())),standing=table.find(r=>own(r.name));
 $('mcOverview').innerHTML=`<div class="mc-summary-grid">${matchCard(live||finished.at(-1),live?'DEVAM EDEN MAÇ':'SON MAÇ')}${matchCard(next,'SIRADAKİ MAÇ')}</div><div class="mc-stats">${[['Lig sırası',standing?standing.position+'.':'–'],['Puan',standing?.points??'–'],['Oynanan',standing?.played??'–'],['Averaj',standing?.gd??'–']].map(([label,value])=>`<div class="mc-stat"><small>${label}</small><strong>${esc(value)}</strong></div>`).join('')}</div><div class="mc-recent"><div class="mc-section-heading"><h2>Son karşılaşmalar</h2>${formHTML(finished)}</div>${finished.slice(-5).reverse().map(row).join('')||'<div class="mc-empty">Henüz tamamlanan maç yok.</div>'}</div>`;
 }
 function renderFixtures(list){const filter=$('mcFilter').value;const filtered=list.filter(m=>filter==='all'||(filter==='scheduled'?['scheduled','postponed'].includes(m.status):m.status===filter));$('mcFixtureList').innerHTML=filtered.map(m=>(m.round?`<div class="mc-round">${m.round}. HAFTA</div>`:'')+row(m)).join('')||'<div class="mc-empty">Seçilen durumda maç bulunmuyor.</div>';}
 function renderStandings(rows){$('mcStandingsTable').innerHTML=rows.length?`<div class="mc-table-wrap"><table class="mc-table"><caption class="sr-only">${esc(currentFeed()?.data?.competition)} puan tablosu</caption><thead><tr><th scope="col">#</th><th scope="col">TAKIM</th><th scope="col">O</th><th scope="col" class="mc-table-secondary">G</th><th scope="col" class="mc-table-secondary">B</th><th scope="col" class="mc-table-secondary">M</th><th scope="col" class="mc-table-extra">A</th><th scope="col" class="mc-table-extra">Y</th><th scope="col">AV</th><th scope="col">P</th></tr></thead><tbody>${rows.map(r=>`<tr class="${own(r.name)?'mc-own':''}"><td>${esc(r.position)}</td><td><span class="mc-table-club">${image(r.logo,'')}${esc(name(r.name))}</span></td><td>${esc(r.played)}</td><td class="mc-table-secondary">${esc(r.won)}</td><td class="mc-table-secondary">${esc(r.drawn)}</td><td class="mc-table-secondary">${esc(r.lost)}</td><td class="mc-table-extra">${esc(r.gf)}</td><td class="mc-table-extra">${esc(r.ga)}</td><td>${esc(r.gd)}</td><td class="mc-points">${esc(r.points)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="mc-empty">Puan tablosu henüz yayımlanmadı.</div>';}
 function showView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$(b.getAttribute('aria-controls')).hidden=!active;});}
 function render(){const feed=currentFeed(),d=feed?.data||{},list=matches(),table=(d.standings||[]).map(r=>({...r}));for(const r of state.manualStandings.filter(r=>r.team_id===ids[state.team]&&r.season===d.season&&r.competition===d.competition)){const v={name:r.team_name,position:r.position,played:r.played,won:r.won,drawn:r.drawn,lost:r.lost,gf:r.goals_for,ga:r.goals_against,gd:r.goal_difference,points:r.points};const i=table.findIndex(x=>x.name===v.name);if(i>=0)table[i]={...table[i],...v};else table.push(v);}table.sort((a,b)=>a.position-b.position);document.querySelectorAll('[data-team]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.team===state.team)));
 $('mcCompetition').textContent=d.season?`${d.competition} · ${d.season}`:'Sezon bilgisi bekleniyor';$('mcRecordCount').textContent=list.length?`${list.length} maç · ${table.length} takım`:'';
 $('mcStandingsSeason').textContent=d.season||'';
 $('mcUpdated').textContent=feed?.last_success_at?'Son kontrol: '+date(feed.last_success_at)+' '+time(feed.last_success_at):'Henüz güncel veri alınamadı';
 const stale=feed?.last_success_at&&Date.now()-stamp(feed.last_success_at)>15*60000;
 const warning=state.lastFetchFailed?'Bağlantı kurulamadı. Son alınan veriler gösteriliyor.':feed?.status==='failed'||stale?'Kaynak güncellemesi gecikti. Son doğrulanan veriler gösteriliyor.':feed?.status==='partial'?'Bazı maç detayları yenilenemedi. Fikstür ve puan tablosu güncellendi.':'';
 $('mcNotice').textContent=warning;$('mcNotice').hidden=!warning;
 $('mcSource').innerHTML=d.source_url?`Veri kaynağı: <a href="${esc(safeUrl(d.source_url))}" target="_blank" rel="noopener noreferrer">${esc(d.source)}</a> · Saatler Türkiye saatidir.`:'';
 for(const [key,id] of [['trabzonspor','mcTsLogo'],['sebat','mcSebatLogo']]){const src=safeUrl(state.feeds.find(f=>f.team_id===ids[key])?.data?.team_logo);if(src){$(id).src=src;$(id).hidden=false;$(id).onerror=()=>{$(id).hidden=true;};}}
 renderOverview(list,table);renderFixtures(list);renderStandings(table);showView(state.view);
 if(dialogMatch&&$('mcDialog').open){const m=list.find(m=>m.id===dialogMatch);if(m)renderDialog(m);}
 }
 function sectionList(title,items){return `<h4>${esc(title)}</h4>`+(items?.length?'<ul>'+items.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>':'<p class="mc-empty">Kaynakta bilgi yayımlanmadı.</p>');}
 function renderDialog(m){$('mcDialogTitle').textContent=name(m.home)+' – '+name(m.away);const d=m.details||{};const side=(key)=>`<section><h3>${esc(name(m[key]))}</h3>${sectionList('İlk 11',d[key]?.lineup)}${sectionList('Yedekler',d[key]?.bench)}${sectionList('Goller',d[key]?.goals)}${sectionList('Kartlar',d[key]?.cards)}${sectionList('Oyuna girenler',d[key]?.substitutions_in)}${sectionList('Oyundan çıkanlar',d[key]?.substitutions_out)}</section>`;
 $('mcDialogBody').innerHTML=`<div class="mc-detail-info"><strong>${score(m)} · ${esc(status(m))}</strong><span>${esc(m.date?date(m.date)+' '+time(m.date):m.date_label||'Tarih açıklanmadı')}</span>${m.venue?'<span>'+esc(m.venue)+'</span>':''}</div>${d.home||d.away?'<div class="mc-detail-cols">'+side('home')+side('away')+'</div>':'<p class="mc-empty">Bu maçın kadro, gol ve kart bilgileri kaynakta henüz yayımlanmadı.</p>'}${d.events?.length?sectionList('Maç olayları',d.events):''}${d.referees?.length?sectionList('Hakemler',d.referees):''}${d.note?'<p class="mc-empty">'+esc(d.note)+'</p>':''}${safeUrl(m.url)?'<a class="mc-source-link" href="'+esc(safeUrl(m.url))+'" target="_blank" rel="noopener noreferrer">Resmî maç kaydını aç ↗</a>':''}`;
 }
 async function read(path){const c=window.AKCAABAT_SUPABASE;if(!c?.url||!c?.key)throw Error('Bağlantı ayarları eksik');const r=await fetch(c.url+'/rest/v1/'+path,{headers:{apikey:c.key,Authorization:'Bearer '+c.key},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Veriler alınamadı');return r.json();}
 async function refresh(){if(state.loading)return;state.loading=true;$('mcRefresh').disabled=true;try{const [feeds,manual,manualStandings]=await Promise.all([read('sports_feeds?select=team_id,data,status,last_success_at'),read('sports_matches?data_source=eq.manual&select=*'),read('sports_standings?is_manual=eq.true&select=*')]);state.feeds=feeds;state.manual=manual;state.manualStandings=manualStandings;state.lastFetchFailed=false;render();}catch{state.lastFetchFailed=true;render();if(!state.feeds.length){$('mcNotice').textContent='Maç verileri şu anda alınamıyor. Yenile düğmesiyle tekrar deneyebilirsin.';$('mcNotice').hidden=false;}}finally{state.loading=false;$('mcRefresh').disabled=false;}}
 document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>{state.team=b.dataset.team;dialogMatch=null;render();}));
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
 document.querySelector('.mc-tabs').addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-view]')],index=tabs.indexOf(document.activeElement);if(index<0)return;let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].focus();showView(tabs[next].dataset.view);}});
 $('mcFilter').addEventListener('change',()=>renderFixtures(matches()));$('mcRefresh').addEventListener('click',refresh);
 document.querySelector('.mc-app').addEventListener('click',e=>{const b=e.target.closest('[data-match]');if(!b)return;const m=matches().find(m=>m.id===b.dataset.match);if(!m)return;dialogMatch=m.id;renderDialog(m);$('mcDialog').showModal();});
 $('mcDialogClose').addEventListener('click',()=>$('mcDialog').close());$('mcDialog').addEventListener('close',()=>{dialogMatch=null;});
 function connect(){if(!window.supabase||!window.AKCAABAT_SUPABASE||channel)return;client=window.supabase.createClient(window.AKCAABAT_SUPABASE.url,window.AKCAABAT_SUPABASE.key);channel=client.channel('sports-feed-public').on('postgres_changes',{event:'UPDATE',schema:'public',table:'sports_feeds'},()=>{if(!document.hidden)refresh();}).on('postgres_changes',{event:'*',schema:'public',table:'sports_matches'},()=>{if(!document.hidden)refresh();}).on('postgres_changes',{event:'*',schema:'public',table:'sports_standings'},()=>{if(!document.hidden)refresh();}).subscribe();}
 function start(){refresh();connect();if(!poll)poll=setInterval(()=>{if(!document.hidden)refresh();},60000);}
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});window.addEventListener('pagehide',()=>{clearInterval(poll);poll=null;if(client&&channel)client.removeChannel(channel);channel=null;});window.addEventListener('pageshow',e=>{if(e.persisted)start();});start();
})();
