(function(){
  'use strict';
  const body=document.body;if(!body)return;body.classList.add('portal-unified');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const now=new Date();
  const header=document.createElement('header');header.className='ah-shell';
  header.innerHTML=`<div class="ah-top"><div class="ah-wrap"><span>${esc(now.toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}</span><div class="ah-top-right"><span>Akçaabat • Trabzon</span><span id="ahClock">${esc(now.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}))}</span></div></div></div><div class="ah-main"><div class="ah-wrap"><a class="ah-brand" href="index.html" aria-label="Akçaabat Haber ana sayfa"><span class="ah-mark">AH</span><span class="ah-brand-copy"><strong>AKÇAABAT</strong><span>HABER</span></span></a><div class="ah-services"><a class="ah-service" href="haber.html">Son Haberler</a><a class="ah-service" href="arama.html">Haber Ara</a><a class="ah-service" href="mac-merkezi.html">Maç Merkezi</a><a class="ah-service" href="canli.html">Canlı Servisler</a></div></div></div><nav class="ah-nav" id="ahNav" aria-label="Ana menü"><div class="ah-wrap"><button class="ah-menu" id="ahMenu" type="button" aria-label="Menüyü aç" aria-expanded="false">☰</button><a href="index.html">Ana Sayfa</a><a href="kategori.html?kategori=Akçaabat">Akçaabat</a><a href="kategori.html?kategori=Trabzon">Trabzon</a><a href="kategori.html?kategori=Trabzonspor">Trabzonspor</a><a href="kategori.html?kategori=Gündem">Gündem</a><a href="kategori.html?kategori=Spor">Spor</a><a href="kategori.html?kategori=Ekonomi">Ekonomi</a><a href="kategori.html?kategori=Asayiş">Asayiş</a><a href="canli.html" class="ah-live">● CANLI</a></div></nav><div class="ah-breaking"><div class="ah-wrap"><span class="ah-breaking-label">SON DAKİKA</span><span class="ah-breaking-text" id="ahBreaking">Akçaabat ve Trabzon'dan son gelişmeler Akçaabat Haber'de.</span></div></div>`;
  body.insertBefore(header,body.firstChild);
  const footer=document.createElement('footer');footer.className='ah-footer';footer.innerHTML=`<div class="ah-wrap ah-footer-top"><div><a class="ah-brand" href="index.html"><span class="ah-mark">AH</span><span class="ah-brand-copy"><strong>AKÇAABAT</strong><span>HABER</span></span></a><p>Akçaabat başta olmak üzere Trabzon'dan güncel yerel haberler, spor ve canlı servisler.</p></div><div><h3>Haberler</h3><a href="kategori.html?kategori=Akçaabat">Akçaabat</a><a href="kategori.html?kategori=Trabzon">Trabzon</a><a href="kategori.html?kategori=Trabzonspor">Trabzonspor</a><a href="haber.html">Son Haberler</a></div><div><h3>Servisler</h3><a href="arama.html">Haber Ara</a><a href="mac-merkezi.html">Maç Merkezi</a><a href="canli.html">Canlı Kameralar & Trafik</a><a href="iletisim.html">İletişim</a></div><div><h3>Kurumsal</h3><a href="hakkimizda.html">Hakkımızda</a><a href="kunye.html">Künye</a><a href="gizlilik.html">Gizlilik</a><a href="kvkk.html">KVKK</a><a href="cerez-politikasi.html">Çerez Politikası</a></div></div><div class="ah-footer-bottom"><div class="ah-wrap">© ${now.getFullYear()} Akçaabat Haber • Tüm hakları saklıdır.</div></div>`;body.appendChild(footer);
  const menu=document.getElementById('ahMenu'),nav=document.getElementById('ahNav');if(menu&&nav)menu.addEventListener('click',()=>{const on=nav.classList.toggle('is-open');menu.setAttribute('aria-expanded',String(on));menu.textContent=on?'✕':'☰'});
  setInterval(()=>{const el=document.getElementById('ahClock');if(el)el.textContent=new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})},30000);
  // Use a real headline already rendered on the page when available; never fabricate live news.
  const candidate=document.querySelector('h1,h2,.news-title,.article-title');if(candidate&&candidate.textContent.trim()){const b=document.getElementById('ahBreaking');if(b)b.textContent=candidate.textContent.trim()}
})();
